import Backend.Db;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Zaki Stivarry
 */

public class Matkul extends javax.swing.JInternalFrame {
    
    public Matkul() {
        initComponents();
        super.setTitle("Data Mata Kuliah");
        
        tampilkan_data();
        kosongkan_form();
    }
    
    private void kosongkan_form(){
        txtkd_matkul.setText("");
        txtnama_matkul.setText("");
        
        simpan.setEnabled(true);
        tbubah.setEnabled(false);
        tbHapus.setEnabled(false);
    }
    
    private void alertWarning(String text) {
        JOptionPane.showMessageDialog(this, text, "Validasi", JOptionPane.WARNING_MESSAGE);
    }
    
    private boolean validasiForm() {
        if(txtkd_matkul.getText().isEmpty()) {
            alertWarning("Kode Matkul tidak boleh kosong");
            return true;
        }else if(txtkd_matkul.getText().length() > 5) {
            alertWarning("Panjang Kode Matkul tidak boleh lebih dari 5 karakter");
            return true;
        }
        
        if(txtnama_matkul.getText().isEmpty()) {
            alertWarning("Nama Matkul tidak boleh kosong");
            return true;
        }else if(txtnama_matkul.getText().length() > 20) {
            alertWarning("Panjang Nama Matkul tidak boleh lebih dari 20 karakter");
            return true;
        }
        
        return false;
    }

    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Kode");
        model.addColumn("Nama Matkul");
        
        try{
            int no = 1;
            ResultSet res = Db.runQuery("SELECT * FROM matkul");
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2)});
            }
            tabelmatkul.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtkd_matkul = new javax.swing.JTextField();
        txtnama_matkul = new javax.swing.JTextField();
        tbTambah = new javax.swing.JButton();
        tbubah = new javax.swing.JButton();
        tbHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmatkul = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Data Mata Kuliah");

        jLabel3.setText("Nama Matkul");

        tbTambah.setText("Reset");
        tbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambahActionPerformed(evt);
            }
        });

        tbubah.setText("Ubah");
        tbubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbubahActionPerformed(evt);
            }
        });

        tbHapus.setText("Hapus");
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });

        tabelmatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelmatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmatkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmatkul);

        jLabel2.setText("Kode Matkul");

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkd_matkul)
                            .addComponent(txtnama_matkul)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(tbTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbubah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnama_matkul)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbubah)
                            .addComponent(tbHapus))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtkd_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambahActionPerformed
        kosongkan_form();
        txtkd_matkul.setEnabled(true);
        txtkd_matkul.setFocusable(true);
    }//GEN-LAST:event_tbTambahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if(!validasiForm()) {
            try{
                Db.runUpdate("CALL proc_insert_matkul("
                    + "'"+txtkd_matkul.getText()+"',"
                    + "'"+txtnama_matkul.getText()+"')");

                JOptionPane.showMessageDialog(null,"Proses Simpan Data Berhasil....");
                tampilkan_data();
                kosongkan_form();
            }catch(HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void tabelmatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmatkulMouseClicked
        int baris = tabelmatkul.rowAtPoint(evt.getPoint());
        
        String kode = tabelmatkul.getValueAt(baris, 1).toString();
        txtkd_matkul.setText(kode);
        txtkd_matkul.setEnabled(false);
        
        String nama = tabelmatkul.getValueAt(baris, 2).toString();
        txtnama_matkul.setText(nama);
        
        simpan.setEnabled(false);
        tbubah.setEnabled(true);
        tbHapus.setEnabled(true);
    }//GEN-LAST:event_tabelmatkulMouseClicked

    private void tbubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbubahActionPerformed
        if(!validasiForm()) {
            try{
                Db.runUpdate("UPDATE matkul SET "
                    + "nama_matkul = '"+ txtnama_matkul.getText() +"'"
                    + "WHERE kd_matkul = '"+ txtkd_matkul.getText() +"'");

                JOptionPane.showMessageDialog(null,"Ubah Data Berhasil...");
            }catch(HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            tampilkan_data();
            kosongkan_form();
            txtkd_matkul.setEnabled(true);
        }
    }//GEN-LAST:event_tbubahActionPerformed

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        try{
            Db.runUpdate("DELETE FROM matkul WHERE kd_matkul='"+ txtkd_matkul.getText() +"'");
            
            JOptionPane.showMessageDialog(null,"Hapus Data Berhasil...");
        }catch(HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        tampilkan_data();
        kosongkan_form();
        txtkd_matkul.setEnabled(true);
    }//GEN-LAST:event_tbHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matkul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelmatkul;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbTambah;
    private javax.swing.JButton tbubah;
    private javax.swing.JTextField txtkd_matkul;
    private javax.swing.JTextField txtnama_matkul;
    // End of variables declaration//GEN-END:variables
}
