import Backend.Db;
import Helper.AutoCompletion;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roby Pangestu
 */

public class Nilai extends javax.swing.JInternalFrame {
    
    DefaultTableModel model;
    
    public Nilai() {
        initComponents();
        super.setTitle("Data Nilai Mahasiswa");
        
        String judul[] = {"NIM", "Mahasiswa", "Mata Kuliah", "Kelas", "Nilai", "Nilai Huruf"};
        model = new DefaultTableModel(judul, 0);
        jTable1.setModel(model);
        
        AutoCompletion.enable(nim);
        
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nilai = new javax.swing.JTextField();
        matkul = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        nim = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        filter = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("NIM");

        tambah.setText("Simpan");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Matkul");

        jLabel4.setText("Nilai");

        matkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --" }));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nilai, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nim, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubah)
                    .addComponent(hapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Data Nilai Mahasiswa");

        jLabel6.setText("Filter Berdasarkan Kelas");

        filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --" }));
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Cari Mahasiswa");

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampil() {
        nim.removeAllItems();
        nim.addItem("-- Pilih --");
        
        matkul.removeAllItems();
        matkul.addItem("-- Pilih --");
        
        int row = jTable1.getRowCount();
        for(int a = 0; a < row; a++){
            model.removeRow(0);
        }
        
        try {
            // List mahasiswa
            ResultSet rsMhs = Db.runQuery("SELECT * FROM view_tampil_nilai");
            while(rsMhs.next()){
                String data[] = {
                    rsMhs.getString("nim"), 
                    rsMhs.getString("nama_mhs"), 
                    rsMhs.getString("nama_matkul"), 
                    rsMhs.getString("nama_kelas"),
                    rsMhs.getString("nilai"),
                    rsMhs.getString("nilai_huruf")
                };
                model.addRow(data);
            }
            
            // List nim
            ResultSet rsNim = Db.runQuery("SELECT * FROM mahasiswa");
            while(rsNim.next()){
                nim.addItem(rsNim.getString("nim")+ " (" +rsNim.getString("nama_mhs") + ")");
            }
            
            // List matkul
            ResultSet rsNilai = Db.runQuery("SELECT * FROM matkul");
            while(rsNilai.next()){
                matkul.addItem(rsNilai.getString("kd_matkul")+ " (" +rsNilai.getString("nama_matkul") + ")");
            }
            
            // List kelas
            ResultSet rsKelas = Db.runQuery("SELECT * FROM kelas");
            ResultSet rsCount = Db.runQuery("SELECT COUNT(id_kelas) AS total FROM kelas");
            rsCount.next();
            while(rsKelas.next()){
                if(filter.getItemCount() <= Integer.parseInt(rsCount.getString("total"))) {
                    filter.addItem(rsKelas.getString("nama_kelas"));
                }
            }
            
            hapus.setEnabled(false);
            ubah.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void reset() {       
        nim.setSelectedIndex(0);
        matkul.setSelectedIndex(0);
        nilai.setText(""); 
    }
    
    private void alertWarning(String text) {
        JOptionPane.showMessageDialog(this, text, "Validasi", JOptionPane.WARNING_MESSAGE);
    }
    
    private boolean validationForm() {
        if(nim.getSelectedItem() == "-- Pilih --") {
            alertWarning("NIM tidak boleh kosong");
            return true;
        }
       
        if(matkul.getSelectedItem() == "-- Pilih --") {
            alertWarning("Pilih salah satu Matkul");
            return true;
        }
        
        if(nilai.getText().isEmpty()) {
            alertWarning("Nilai tidak boleh kosong");
            return true;
        }else if(nilai.getText().length() > 3) {
            alertWarning("Panjang Nilai tidak boleh lebih dari 3 karakter");
            return true;
        }
        
        return false;
    }
    
    private void updateNilai() {
        try {
            String[] partMatkul = matkul.getSelectedItem().toString().split(" ");
            String[] partNim = nim.getSelectedItem().toString().split(" ");

            ResultSet rsNilaiHuruf = Db.runQuery("SELECT func_nilai_huruf("+ Integer.parseInt(nilai.getText()) +") AS nilai_huruf");

            if(rsNilaiHuruf.next()) {
                Db.runUpdate("UPDATE nilai SET " +
                    "nim = '" + partNim[0] + "'," +
                    "nilai = "  + nilai.getText() + "," +
                    "nilai_huruf = '"+ rsNilaiHuruf.getString("nilai_huruf") + "'," +
                    "kd_matkul = '"  + partMatkul[0] + "' WHERE nim = '" + partNim[0] + "' " + 
                    "AND kd_matkul = '"+ partMatkul[0] +"'");

                tampil();
                tambah.setEnabled(true);
                reset();

                JOptionPane.showMessageDialog(this, "Data Berhasil Di update");
            }else{
                JOptionPane.showMessageDialog(this, "Terdapat kesalahan pana nilai huruf", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        if(!validationForm()) {
            try {
                String[] partMatkul = matkul.getSelectedItem().toString().split(" ");
                String[] partNim = nim.getSelectedItem().toString().split(" ");
                
                ResultSet rsCekDuplikat = Db.runQuery("SELECT COUNT('id_nilai') AS cek FROM nilai WHERE "
                    + " nim = '"+ partNim[0] +"' "
                    + "AND kd_matkul = '"+ partMatkul[0] +"'");
                
                if(rsCekDuplikat.next()) {
                    if(Integer.parseInt(rsCekDuplikat.getString("cek")) == 0) {
                        ResultSet rsNilaiHuruf = Db.runQuery("SELECT func_nilai_huruf("+ Integer.parseInt(nilai.getText()) +") AS nilai_huruf");

                        if(rsNilaiHuruf.next()) {
                            Db.runUpdate("CALL proc_insert_nilai " 
                                + "('" + partNim[0] + "'," 
                                + "'"  + partMatkul[0] + "',"
                                + Integer.parseInt(nilai.getText()) + ","
                                + "'"+ rsNilaiHuruf.getString("nilai_huruf") +"')");

                            tampil();
                            reset();

                            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambah");
                        }else{
                            JOptionPane.showMessageDialog(this, "Terdapat kesalahan pana nilai huruf", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        updateNilai();
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Terdapat kesalahan", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int a = jTable1.getSelectedRow();
        if (a > -1){
            nim.setSelectedItem(model.getValueAt(a, 0).toString() + " ("+ model.getValueAt(a, 1).toString() +")");
            matkul.setSelectedItem(model.getValueAt(a, 2).toString());
            nilai.setText(model.getValueAt(a, 4).toString());
            
            String modelMatkul = "("+ model.getValueAt(a, 2).toString() +")";
            for(int i = 0; i <= matkul.getComponentCount(); i++) {
                String[] part = matkul.getItemAt(i).split(" ");

                if(part[1].equals(modelMatkul)) {
                    matkul.setSelectedIndex(i);
                    break;
                }
            }
            
            hapus.setEnabled(true);
            ubah.setEnabled(true);
            tambah.setEnabled(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        int row = jTable1.getRowCount();
        for(int a = 0; a < row; a++){
            model.removeRow(0);
        }
        
        if(filter.getSelectedItem() != "-- Pilih --"){
            try {
                ResultSet rsMhs = Db.runQuery("SELECT * FROM view_tampil_nilai WHERE nama_kelas = '" + filter.getSelectedItem() + "'");

                while(rsMhs.next()){
                    String data[] = {
                        rsMhs.getString("nim"), 
                        rsMhs.getString("nama_mhs"), 
                        rsMhs.getString("nama_matkul"), 
                        rsMhs.getString("nama_kelas"),
                        rsMhs.getString("nilai"),
                        rsMhs.getString("nilai_huruf")
                    };
                    model.addRow(data);                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            tampil();
        }
    }//GEN-LAST:event_filterActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Yakin");
        
        if(a == 0){
            String[] partMatkul = matkul.getSelectedItem().toString().split(" ");
            String[] partNim = nim.getSelectedItem().toString().split(" ");
                
            try {
               Db.runUpdate("DELETE FROM nilai WHERE nim = '"+ partNim[0] +"' AND kd_matkul = '"+ partMatkul[0] +"'");
               
               tampil();
               tambah.setEnabled(true);
               reset();
            } catch (SQLException ex) {
               Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }        
    }//GEN-LAST:event_hapusActionPerformed
    
    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        if(!validationForm()) {
            updateNilai();
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nim.setSelectedItem("-- Pilih --");
        matkul.setSelectedItem("-- Pilih --");
        nilai.setText("");
        
        tambah.setEnabled(true);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        int row = jTable1.getRowCount();
        for(int a = 0; a < row; a++){
            model.removeRow(0);
        }
        
        try {
            ResultSet rs = Db.runQuery("SELECT * FROM view_tampil_nilai WHERE "
                    + "nama_mhs LIKE '%"+ search.getText() +"%'"
                    + "OR nim LIKE '%"+ search.getText() +"%'");

            while(rs.next()){
                String data[] = {
                    rs.getString("nim"), 
                    rs.getString("nama_mhs"), 
                    rs.getString("nama_matkul"), 
                    rs.getString("nama_kelas"),
                    rs.getString("nilai"),
                    rs.getString("nilai_huruf")
                };
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> filter;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> matkul;
    private javax.swing.JTextField nilai;
    private javax.swing.JComboBox<String> nim;
    private javax.swing.JTextField search;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

}